// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkuhiy3EbQzFQxTI1-gnZbjo6yUqova-A',
    appId: '1:205804755562:web:712c6a1a9eaa08a4090813',
    messagingSenderId: '205804755562',
    projectId: 'yeterlyai-sign2text',
    authDomain: 'yeterlyai-sign2text.firebaseapp.com',
    storageBucket: 'yeterlyai-sign2text.firebasestorage.app',
    measurementId: 'G-5WQLSZW6GH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0QkOiVrtqXbOqsqQH_2tGC1HmIcP56eg',
    appId: '1:205804755562:android:9b2a2db3f7f55a7b090813',
    messagingSenderId: '205804755562',
    projectId: 'yeterlyai-sign2text',
    storageBucket: 'yeterlyai-sign2text.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwwEE9uRaGU05AsNBwGvarKiH7iIKgSXU',
    appId: '1:205804755562:ios:f1dfcbed3d7690e6090813',
    messagingSenderId: '205804755562',
    projectId: 'yeterlyai-sign2text',
    storageBucket: 'yeterlyai-sign2text.firebasestorage.app',
    iosBundleId: 'com.example.aslTranslator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwwEE9uRaGU05AsNBwGvarKiH7iIKgSXU',
    appId: '1:205804755562:ios:f1dfcbed3d7690e6090813',
    messagingSenderId: '205804755562',
    projectId: 'yeterlyai-sign2text',
    storageBucket: 'yeterlyai-sign2text.firebasestorage.app',
    iosBundleId: 'com.example.aslTranslator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkuhiy3EbQzFQxTI1-gnZbjo6yUqova-A',
    appId: '1:205804755562:web:d41b0ef77b97a3d4090813',
    messagingSenderId: '205804755562',
    projectId: 'yeterlyai-sign2text',
    authDomain: 'yeterlyai-sign2text.firebaseapp.com',
    storageBucket: 'yeterlyai-sign2text.firebasestorage.app',
    measurementId: 'G-3STCBQWLN7',
  );
}
