name: sign2text
description: "Sign language translation application"

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  google_sign_in: ^6.1.6
  
  # Camera and Image Processing
  camera: ^0.11.0+2
  path_provider: ^2.1.1
  path: ^1.8.3
  image: ^4.1.3
  image_picker: ^1.1.2
  
  # ML and Processing
  tflite_flutter: ^0.11.0
  
  # UI and State Management
  provider: ^6.1.1
  http: ^1.2.2
  iconsax_flutter: ^1.0.0
  cupertino_icons: ^1.0.8
  package_info_plus: ^8.1.1
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/images/
    - assets/logos/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-VariableFont_wght.ttf
          weight: 400